/**
 * MVPソース定義
 * 公式一次情報を最優先に定義
 */

export interface SourceDefinition {
  name: string;
  slug: string;
  type: "OFFICIAL" | "RSS" | "GITHUB" | "X";
  url: string;
  feedUrl?: string;
  fetchMethod: "rss" | "html" | "github-releases" | "x-api" | "x-search";
  trustScore: number;
  frequency: "HOURLY" | "DAILY" | "WEEKLY";
  legalNotes?: string;
  /** 自動タグ付け用: プロダクトタグのslug */
  productTagSlugs: string[];
}

export const MVP_SOURCES: SourceDefinition[] = [
  // === OpenAI ===
  {
    name: "ChatGPT リリースノート（日本語）",
    slug: "chatgpt-release-notes-ja",
    type: "OFFICIAL",
    url: "https://help.openai.com/ja-jp/articles/6825453-chatgpt-%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%83%8E%E3%83%BC%E3%83%88",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式ヘルプページ。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "ChatGPT Release Notes (EN)",
    slug: "chatgpt-release-notes-en",
    type: "OFFICIAL",
    url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式ヘルプページ。要約・引用のみ。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "OpenAI Developers Changelog",
    slug: "openai-developers-changelog",
    type: "RSS",
    url: "https://developers.openai.com/changelog/",
    feedUrl: "https://developers.openai.com/changelog/rss.xml",
    fetchMethod: "rss",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式Developer changelog。RSS配信あり。",
    productTagSlugs: ["openai-api"],
  },

  // === Anthropic ===
  {
    name: "Claude Developer Platform Release Notes",
    slug: "claude-platform-release-notes",
    type: "OFFICIAL",
    url: "https://docs.anthropic.com/en/docs/about-claude/models",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式リリースノート。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Claude Code GitHub Releases",
    slug: "claude-code-github-releases",
    type: "GITHUB",
    url: "https://github.com/anthropics/claude-code",
    fetchMethod: "github-releases",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes:
      "GitHub REST API利用。レート制限（未認証60回/時）を遵守。",
    productTagSlugs: ["claude-code", "claude"],
  },

  // === Google Gemini ===
  {
    name: "Gemini アプリ リリースノート（日本語）",
    slug: "gemini-app-release-notes-ja",
    type: "OFFICIAL",
    url: "https://blog.google/products/gemini/",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式リリースノート。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Gemini API Changelog",
    slug: "gemini-api-changelog",
    type: "OFFICIAL",
    url: "https://ai.google.dev/gemini-api/docs/changelog",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "公式API changelog。",
    productTagSlugs: ["gemini"],
  },

  // === コミュニティブログ（一般の人の記事） ===
  // 吉田ペルソナ（Biz実装層/L1-L2）に刺さる実践的な記事を収集
  {
    name: "Zenn — ChatGPT",
    slug: "zenn-chatgpt",
    type: "RSS",
    url: "https://zenn.dev/topics/chatgpt",
    feedUrl: "https://zenn.dev/topics/chatgpt/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "Zenn — Claude",
    slug: "zenn-claude",
    type: "RSS",
    url: "https://zenn.dev/topics/claude",
    feedUrl: "https://zenn.dev/topics/claude/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Zenn — Gemini",
    slug: "zenn-gemini",
    type: "RSS",
    url: "https://zenn.dev/topics/gemini",
    feedUrl: "https://zenn.dev/topics/gemini/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Zenn — 生成AI活用",
    slug: "zenn-generative-ai",
    type: "RSS",
    url: "https://zenn.dev/topics/生成ai",
    feedUrl: "https://zenn.dev/topics/%E7%94%9F%E6%88%90ai/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Qiita — ChatGPT",
    slug: "qiita-chatgpt",
    type: "RSS",
    url: "https://qiita.com/tags/chatgpt",
    feedUrl: "https://qiita.com/tags/chatgpt/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "Qiita — Claude",
    slug: "qiita-claude",
    type: "RSS",
    url: "https://qiita.com/tags/claude",
    feedUrl: "https://qiita.com/tags/claude/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Qiita — 生成AI",
    slug: "qiita-generative-ai",
    type: "RSS",
    url: "https://qiita.com/tags/生成ai",
    feedUrl: "https://qiita.com/tags/%E7%94%9F%E6%88%90ai/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AI活用",
    slug: "note-ai",
    type: "RSS",
    url: "https://note.com/hashtag/AI活用",
    feedUrl: "https://note.com/hashtag/AI%E6%B4%BB%E7%94%A8/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — ChatGPT活用",
    slug: "note-chatgpt",
    type: "RSS",
    url: "https://note.com/hashtag/ChatGPT活用",
    feedUrl: "https://note.com/hashtag/ChatGPT%E6%B4%BB%E7%94%A8/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "note — Claude活用",
    slug: "note-claude",
    type: "RSS",
    url: "https://note.com/hashtag/Claude",
    feedUrl: "https://note.com/hashtag/Claude/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["claude"],
  },
  {
    name: "note — Gemini",
    slug: "note-gemini",
    type: "RSS",
    url: "https://note.com/hashtag/Gemini",
    feedUrl: "https://note.com/hashtag/Gemini/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "note — 生成AI",
    slug: "note-generative-ai",
    type: "RSS",
    url: "https://note.com/hashtag/生成AI",
    feedUrl: "https://note.com/hashtag/%E7%94%9F%E6%88%90AI/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AIまとめ",
    slug: "note-ai-matome",
    type: "RSS",
    url: "https://note.com/hashtag/AIまとめ",
    feedUrl: "https://note.com/hashtag/AI%E3%81%BE%E3%81%A8%E3%82%81/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AIツール",
    slug: "note-ai-tools",
    type: "RSS",
    url: "https://note.com/hashtag/AIツール",
    feedUrl: "https://note.com/hashtag/AI%E3%83%84%E3%83%BC%E3%83%AB/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AIおすすめ",
    slug: "note-ai-recommend",
    type: "RSS",
    url: "https://note.com/hashtag/AIおすすめ",
    feedUrl: "https://note.com/hashtag/AI%E3%81%8A%E3%81%99%E3%81%99%E3%82%81/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — プロンプト",
    slug: "note-prompt",
    type: "RSS",
    url: "https://note.com/hashtag/プロンプト",
    feedUrl: "https://note.com/hashtag/%E3%83%97%E3%83%AD%E3%83%B3%E3%83%97%E3%83%88/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Zenn — AI",
    slug: "zenn-ai",
    type: "RSS",
    url: "https://zenn.dev/topics/ai",
    feedUrl: "https://zenn.dev/topics/ai/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Qiita — Gemini",
    slug: "qiita-gemini",
    type: "RSS",
    url: "https://qiita.com/tags/gemini",
    feedUrl: "https://qiita.com/tags/gemini/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Qiita — LLM",
    slug: "qiita-llm",
    type: "RSS",
    url: "https://qiita.com/tags/llm",
    feedUrl: "https://qiita.com/tags/llm/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Qiita — プロンプトエンジニアリング",
    slug: "qiita-prompt-engineering",
    type: "RSS",
    url: "https://qiita.com/tags/promptengineering",
    feedUrl: "https://qiita.com/tags/promptengineering/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Zenn — プロンプトエンジニアリング",
    slug: "zenn-prompt-engineering",
    type: "RSS",
    url: "https://zenn.dev/topics/promptengineering",
    feedUrl: "https://zenn.dev/topics/promptengineering/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Zenn — LLM",
    slug: "zenn-llm",
    type: "RSS",
    url: "https://zenn.dev/topics/llm",
    feedUrl: "https://zenn.dev/topics/llm/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },

  // === X（速報補助・規約遵守: APIのみ） ===
  {
    name: "X — OpenAI 公式",
    slug: "x-openai",
    type: "X",
    url: "https://x.com/OpenAI",
    fetchMethod: "x-api",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "X API v2利用。スクレイピング禁止。速報補助として扱い、裏取り前は隔離ラベル付き。",
    productTagSlugs: ["chatgpt", "openai-api"],
  },
  {
    name: "X — Anthropic 公式",
    slug: "x-anthropic",
    type: "X",
    url: "https://x.com/AnthropicAI",
    fetchMethod: "x-api",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "X API v2利用。スクレイピング禁止。速報補助として扱い、裏取り前は隔離ラベル付き。",
    productTagSlugs: ["claude", "claude-code"],
  },
  {
    name: "X — Google DeepMind 公式",
    slug: "x-google-deepmind",
    type: "X",
    url: "https://x.com/GoogleDeepMind",
    fetchMethod: "x-api",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "X API v2利用。スクレイピング禁止。速報補助として扱い、裏取り前は隔離ラベル付き。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "X — AI活用トピック検索",
    slug: "x-ai-topics",
    type: "X",
    url: "https://x.com/search",
    fetchMethod: "x-search",
    trustScore: 30,
    frequency: "HOURLY",
    legalNotes: "X API v2 search/recent利用。スクレイピング禁止。速報ラベルで隔離。裏取り必須。",
    productTagSlugs: [],
  },

  // === ポーカー ===
  {
    name: "PokerNews — 最新ニュース",
    slug: "pokernews-latest",
    type: "RSS",
    url: "https://www.pokernews.com/",
    feedUrl: "https://www.pokernews.com/rss/news.xml",
    fetchMethod: "rss",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "PokerNewsのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "WSOP 公式ニュース",
    slug: "wsop-news",
    type: "OFFICIAL",
    url: "https://www.wsop.com/news/",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "WSOP公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "JOPT — Japan Open Poker Tour",
    slug: "jopt-news",
    type: "OFFICIAL",
    url: "https://japanopenpoker.com/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "JOPT公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "GTO Wizard — ブログ",
    slug: "gto-wizard-blog",
    type: "RSS",
    url: "https://blog.gtowizard.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "GTO Wizard公式ブログ。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },

  // === AV（アダルトビデオ業界情報） ===
  {
    name: "FANZA ニュースリリース",
    slug: "fanza-news",
    type: "OFFICIAL",
    url: "https://www.dmm.co.jp/digital/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "FANZA公式サイト。ランキング・新着情報の要約のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "moodyz 新作情報",
    slug: "moodyz-new",
    type: "OFFICIAL",
    url: "https://www.moodyz.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "S1 新作情報",
    slug: "s1-new",
    type: "OFFICIAL",
    url: "https://www.s1s1s1.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },

  // === 大阪ローカル ===
  {
    name: "大阪オンライン — イベント",
    slug: "osaka-online-events",
    type: "RSS",
    url: "https://osaka-online.jp/",
    fetchMethod: "html",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "大阪オンライン。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
  {
    name: "ウォーカープラス大阪 — グルメ",
    slug: "walkerplus-osaka-gourmet",
    type: "RSS",
    url: "https://www.walkerplus.com/event_list/ar0727/eg0117/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "ウォーカープラス。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
  {
    name: "食べログ大阪 — 新規オープン",
    slug: "tabelog-osaka-new",
    type: "RSS",
    url: "https://tabelog.com/osaka/C27100/rstLst/cond16-00-00/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "食べログ。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },

  // === 起業（スタートアップ） ===
  {
    name: "TechCrunch Japan",
    slug: "techcrunch-japan",
    type: "RSS",
    url: "https://jp.techcrunch.com/",
    feedUrl: "https://jp.techcrunch.com/feed/",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "TechCrunch Japan RSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "PR TIMES — スタートアップ",
    slug: "prtimes-startup",
    type: "RSS",
    url: "https://prtimes.jp/topics/keywords/スタートアップ",
    feedUrl: "https://prtimes.jp/topics/keywords/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%A2%E3%83%83%E3%83%97/feed",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "PR TIMES RSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "BRIDGE — スタートアップニュース",
    slug: "bridge-startup",
    type: "RSS",
    url: "https://thebridge.jp/",
    feedUrl: "https://thebridge.jp/feed",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "BRIDGE RSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "note — 起業",
    slug: "note-startup",
    type: "RSS",
    url: "https://note.com/hashtag/起業",
    feedUrl: "https://note.com/hashtag/%E8%B5%B7%E6%A5%AD/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "note — スタートアップ",
    slug: "note-startup-tag",
    type: "RSS",
    url: "https://note.com/hashtag/スタートアップ",
    feedUrl: "https://note.com/hashtag/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%A2%E3%83%83%E3%83%97/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },

  // === ウズベキスタン ===
  {
    name: "在日ウズベキスタン大使館",
    slug: "uzbek-embassy-japan",
    type: "OFFICIAL",
    url: "https://uzbekistan.jp/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "大使館公式サイト。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },
  {
    name: "JETRO — ウズベキスタン",
    slug: "jetro-uzbekistan",
    type: "OFFICIAL",
    url: "https://www.jetro.go.jp/world/russia_cis/uz/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "JETRO公式サイト。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },
  {
    name: "note — ウズベキスタン",
    slug: "note-uzbekistan",
    type: "RSS",
    url: "https://note.com/hashtag/ウズベキスタン",
    feedUrl: "https://note.com/hashtag/%E3%82%A6%E3%82%BA%E3%83%99%E3%82%AD%E3%82%B9%E3%82%BF%E3%83%B3/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },

  // === ホテル・ホテルマネジメント ===
  {
    name: "トラベルジャーナル",
    slug: "travel-journal",
    type: "OFFICIAL",
    url: "https://www.tjnet.co.jp/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "トラベルジャーナル公式サイト。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "観光経済新聞",
    slug: "kankokeizai",
    type: "OFFICIAL",
    url: "https://www.kankokeizai.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "観光経済新聞公式サイト。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "HOTERES — ホテル業界ニュース",
    slug: "hoteres-news",
    type: "OFFICIAL",
    url: "https://www.hoteresonline.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "HOTERES公式サイト。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "note — ホテル",
    slug: "note-hotel",
    type: "RSS",
    url: "https://note.com/hashtag/ホテル",
    feedUrl: "https://note.com/hashtag/%E3%83%9B%E3%83%86%E3%83%AB/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },

  // === 香水 ===
  {
    name: "Fragrantica — 新着香水",
    slug: "fragrantica-new",
    type: "OFFICIAL",
    url: "https://www.fragrantica.com/newperfumes/",
    fetchMethod: "html",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "Fragrantica公式サイト。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "note — 香水",
    slug: "note-perfume",
    type: "RSS",
    url: "https://note.com/hashtag/香水",
    feedUrl: "https://note.com/hashtag/%E9%A6%99%E6%B0%B4/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "Zenn — 香水",
    slug: "zenn-perfume",
    type: "RSS",
    url: "https://zenn.dev/topics/perfume",
    feedUrl: "https://zenn.dev/topics/perfume/feed",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "@cosme — 香水ランキング",
    slug: "cosme-perfume-ranking",
    type: "OFFICIAL",
    url: "https://www.cosme.net/rankings/category/0110009",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "@cosme公式サイト。ランキング要約のみ。",
    productTagSlugs: ["perfume"],
  },

  // === ガジェット ===
  {
    name: "GIZMODO Japan",
    slug: "gizmodo-japan",
    type: "RSS",
    url: "https://www.gizmodo.jp/",
    feedUrl: "https://www.gizmodo.jp/feed/",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "GIZMODO Japan RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "Engadget 日本版",
    slug: "engadget-japan",
    type: "RSS",
    url: "https://japanese.engadget.com/",
    feedUrl: "https://japanese.engadget.com/rss.xml",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "Engadget日本版RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "note — ガジェット",
    slug: "note-gadget",
    type: "RSS",
    url: "https://note.com/hashtag/ガジェット",
    feedUrl: "https://note.com/hashtag/%E3%82%AC%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "ITmedia — ガジェット",
    slug: "itmedia-gadget",
    type: "RSS",
    url: "https://www.itmedia.co.jp/mobile/",
    feedUrl: "https://rss.itmedia.co.jp/rss/2.0/mobile.xml",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "ITmedia RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },

  // === 大阪風俗 ===
  {
    name: "シティヘブンネット大阪",
    slug: "cityheaven-osaka",
    type: "OFFICIAL",
    url: "https://cityheaven.net/osaka/",
    fetchMethod: "html",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "シティヘブンネット公式サイト。店舗情報の要約のみ。",
    productTagSlugs: ["osaka-fuzoku"],
  },
];
