/**
 * MVPソース定義
 * 公式一次情報を最優先に定義
 */

export interface SourceDefinition {
  name: string;
  slug: string;
  type: "OFFICIAL" | "RSS" | "GITHUB" | "X";
  url: string;
  feedUrl?: string;
  fetchMethod: "rss" | "html" | "github-releases" | "x-api" | "x-search";
  trustScore: number;
  frequency: "HOURLY" | "DAILY" | "WEEKLY";
  legalNotes?: string;
  /** 自動タグ付け用: プロダクトタグのslug */
  productTagSlugs: string[];
}

export const MVP_SOURCES: SourceDefinition[] = [
  // === OpenAI ===
  {
    name: "ChatGPT リリースノート（日本語）",
    slug: "chatgpt-release-notes-ja",
    type: "OFFICIAL",
    url: "https://help.openai.com/ja-jp/articles/6825453-chatgpt-%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%83%8E%E3%83%BC%E3%83%88",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式ヘルプページ。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "ChatGPT Release Notes (EN)",
    slug: "chatgpt-release-notes-en",
    type: "OFFICIAL",
    url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式ヘルプページ。要約・引用のみ。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "OpenAI Developers Changelog",
    slug: "openai-developers-changelog",
    type: "RSS",
    url: "https://developers.openai.com/changelog/",
    feedUrl: "https://developers.openai.com/changelog/rss.xml",
    fetchMethod: "rss",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式Developer changelog。RSS配信あり。",
    productTagSlugs: ["openai-api"],
  },

  // === Anthropic ===
  {
    name: "Claude Developer Platform Release Notes",
    slug: "claude-platform-release-notes",
    type: "OFFICIAL",
    url: "https://docs.anthropic.com/en/docs/about-claude/models",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式リリースノート。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Claude Code GitHub Releases",
    slug: "claude-code-github-releases",
    type: "GITHUB",
    url: "https://github.com/anthropics/claude-code",
    fetchMethod: "github-releases",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes:
      "GitHub REST API利用。レート制限（未認証60回/時）を遵守。",
    productTagSlugs: ["claude-code", "claude"],
  },

  // === Google Gemini ===
  {
    name: "Gemini アプリ リリースノート（日本語）",
    slug: "gemini-app-release-notes-ja",
    type: "OFFICIAL",
    url: "https://blog.google/products/gemini/",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "公式リリースノート。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Gemini API Changelog",
    slug: "gemini-api-changelog",
    type: "OFFICIAL",
    url: "https://ai.google.dev/gemini-api/docs/changelog",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "公式API changelog。",
    productTagSlugs: ["gemini"],
  },

  // === コミュニティブログ（一般の人の記事） ===
  // 吉田ペルソナ（Biz実装層/L1-L2）に刺さる実践的な記事を収集
  {
    name: "Zenn — ChatGPT",
    slug: "zenn-chatgpt",
    type: "RSS",
    url: "https://zenn.dev/topics/chatgpt",
    feedUrl: "https://zenn.dev/topics/chatgpt/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "Zenn — Claude",
    slug: "zenn-claude",
    type: "RSS",
    url: "https://zenn.dev/topics/claude",
    feedUrl: "https://zenn.dev/topics/claude/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Zenn — Gemini",
    slug: "zenn-gemini",
    type: "RSS",
    url: "https://zenn.dev/topics/gemini",
    feedUrl: "https://zenn.dev/topics/gemini/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Zenn — 生成AI活用",
    slug: "zenn-generative-ai",
    type: "RSS",
    url: "https://zenn.dev/topics/生成ai",
    feedUrl: "https://zenn.dev/topics/%E7%94%9F%E6%88%90ai/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Qiita — ChatGPT",
    slug: "qiita-chatgpt",
    type: "RSS",
    url: "https://qiita.com/tags/chatgpt",
    feedUrl: "https://qiita.com/tags/chatgpt/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "Qiita — Claude",
    slug: "qiita-claude",
    type: "RSS",
    url: "https://qiita.com/tags/claude",
    feedUrl: "https://qiita.com/tags/claude/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Qiita — 生成AI",
    slug: "qiita-generative-ai",
    type: "RSS",
    url: "https://qiita.com/tags/生成ai",
    feedUrl: "https://qiita.com/tags/%E7%94%9F%E6%88%90ai/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AI活用",
    slug: "note-ai",
    type: "RSS",
    url: "https://note.com/hashtag/AI活用",
    feedUrl: "https://note.com/hashtag/AI%E6%B4%BB%E7%94%A8/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — ChatGPT活用",
    slug: "note-chatgpt",
    type: "RSS",
    url: "https://note.com/hashtag/ChatGPT活用",
    feedUrl: "https://note.com/hashtag/ChatGPT%E6%B4%BB%E7%94%A8/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "note — Claude活用",
    slug: "note-claude",
    type: "RSS",
    url: "https://note.com/hashtag/Claude",
    feedUrl: "https://note.com/hashtag/Claude/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["claude"],
  },
  {
    name: "note — Gemini",
    slug: "note-gemini",
    type: "RSS",
    url: "https://note.com/hashtag/Gemini",
    feedUrl: "https://note.com/hashtag/Gemini/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "note — 生成AI",
    slug: "note-generative-ai",
    type: "RSS",
    url: "https://note.com/hashtag/生成AI",
    feedUrl: "https://note.com/hashtag/%E7%94%9F%E6%88%90AI/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AIまとめ",
    slug: "note-ai-matome",
    type: "RSS",
    url: "https://note.com/hashtag/AIまとめ",
    feedUrl: "https://note.com/hashtag/AI%E3%81%BE%E3%81%A8%E3%82%81/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AIツール",
    slug: "note-ai-tools",
    type: "RSS",
    url: "https://note.com/hashtag/AIツール",
    feedUrl: "https://note.com/hashtag/AI%E3%83%84%E3%83%BC%E3%83%AB/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — AIおすすめ",
    slug: "note-ai-recommend",
    type: "RSS",
    url: "https://note.com/hashtag/AIおすすめ",
    feedUrl: "https://note.com/hashtag/AI%E3%81%8A%E3%81%99%E3%81%99%E3%82%81/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "note — プロンプト",
    slug: "note-prompt",
    type: "RSS",
    url: "https://note.com/hashtag/プロンプト",
    feedUrl: "https://note.com/hashtag/%E3%83%97%E3%83%AD%E3%83%B3%E3%83%97%E3%83%88/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Zenn — AI",
    slug: "zenn-ai",
    type: "RSS",
    url: "https://zenn.dev/topics/ai",
    feedUrl: "https://zenn.dev/topics/ai/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Qiita — Gemini",
    slug: "qiita-gemini",
    type: "RSS",
    url: "https://qiita.com/tags/gemini",
    feedUrl: "https://qiita.com/tags/gemini/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Qiita — LLM",
    slug: "qiita-llm",
    type: "RSS",
    url: "https://qiita.com/tags/llm",
    feedUrl: "https://qiita.com/tags/llm/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Qiita — プロンプトエンジニアリング",
    slug: "qiita-prompt-engineering",
    type: "RSS",
    url: "https://qiita.com/tags/promptengineering",
    feedUrl: "https://qiita.com/tags/promptengineering/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "QiitaのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Zenn — プロンプトエンジニアリング",
    slug: "zenn-prompt-engineering",
    type: "RSS",
    url: "https://zenn.dev/topics/promptengineering",
    feedUrl: "https://zenn.dev/topics/promptengineering/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },
  {
    name: "Zenn — LLM",
    slug: "zenn-llm",
    type: "RSS",
    url: "https://zenn.dev/topics/llm",
    feedUrl: "https://zenn.dev/topics/llm/feed",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。全文転載禁止。",
    productTagSlugs: [],
  },

  // === X（速報補助・規約遵守: APIのみ） ===
  {
    name: "X — OpenAI 公式",
    slug: "x-openai",
    type: "X",
    url: "https://x.com/OpenAI",
    fetchMethod: "x-api",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "X API v2利用。スクレイピング禁止。速報補助として扱い、裏取り前は隔離ラベル付き。",
    productTagSlugs: ["chatgpt", "openai-api"],
  },
  {
    name: "X — Anthropic 公式",
    slug: "x-anthropic",
    type: "X",
    url: "https://x.com/AnthropicAI",
    fetchMethod: "x-api",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "X API v2利用。スクレイピング禁止。速報補助として扱い、裏取り前は隔離ラベル付き。",
    productTagSlugs: ["claude", "claude-code"],
  },
  {
    name: "X — Google DeepMind 公式",
    slug: "x-google-deepmind",
    type: "X",
    url: "https://x.com/GoogleDeepMind",
    fetchMethod: "x-api",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "X API v2利用。スクレイピング禁止。速報補助として扱い、裏取り前は隔離ラベル付き。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "X — AI活用トピック検索",
    slug: "x-ai-topics",
    type: "X",
    url: "https://x.com/search",
    fetchMethod: "x-search",
    trustScore: 30,
    frequency: "HOURLY",
    legalNotes: "X API v2 search/recent利用。スクレイピング禁止。速報ラベルで隔離。裏取り必須。",
    productTagSlugs: [],
  },

  // === ポーカー ===
  {
    name: "PokerNews — 最新ニュース",
    slug: "pokernews-latest",
    type: "RSS",
    url: "https://www.pokernews.com/",
    feedUrl: "https://www.pokernews.com/rss/news.xml",
    fetchMethod: "rss",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "PokerNewsのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "WSOP 公式ニュース",
    slug: "wsop-news",
    type: "OFFICIAL",
    url: "https://www.wsop.com/news/",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "WSOP公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "JOPT — Japan Open Poker Tour",
    slug: "jopt-news",
    type: "OFFICIAL",
    url: "https://japanopenpoker.com/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "JOPT公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "GTO Wizard — ブログ",
    slug: "gto-wizard-blog",
    type: "RSS",
    url: "https://blog.gtowizard.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "GTO Wizard公式ブログ。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "CardPlayer — ニュース",
    slug: "cardplayer-news",
    type: "RSS",
    url: "https://www.cardplayer.com/",
    feedUrl: "https://www.cardplayer.com/rss/poker-news.xml",
    fetchMethod: "rss",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "CardPlayer RSSフィード。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "WPT 公式ニュース",
    slug: "wpt-news",
    type: "OFFICIAL",
    url: "https://www.worldpokertour.com/news/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "WPT公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "PokerStars Blog",
    slug: "pokerstars-blog",
    type: "OFFICIAL",
    url: "https://www.pokerstars.com/en/blog/",
    fetchMethod: "html",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "PokerStars公式ブログ。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "GGPoker ニュース",
    slug: "ggpoker-news",
    type: "OFFICIAL",
    url: "https://www.ggpoker.com/news/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "GGPoker公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "Upswing Poker — 戦略記事",
    slug: "upswing-poker",
    type: "OFFICIAL",
    url: "https://upswingpoker.com/blog/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "Upswing Poker公式ブログ。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "AJPC — 全日本ポーカー選手権",
    slug: "ajpc-news",
    type: "OFFICIAL",
    url: "https://ajpc.jp/",
    fetchMethod: "html",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "AJPC公式サイト。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "Hendon Mob — トーナメント結果",
    slug: "hendonmob-results",
    type: "OFFICIAL",
    url: "https://www.thehendonmob.com/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "The Hendon Mob公式サイト。結果要約のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "Google News — ポーカー速報",
    slug: "gnews-poker",
    type: "RSS",
    url: "https://news.google.com/search?q=ポーカー+大会",
    feedUrl: "https://news.google.com/rss/search?q=%E3%83%9D%E3%83%BC%E3%82%AB%E3%83%BC+%E5%A4%A7%E4%BC%9A&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "Google News — WSOP",
    slug: "gnews-wsop",
    type: "RSS",
    url: "https://news.google.com/search?q=WSOP+poker",
    feedUrl: "https://news.google.com/rss/search?q=WSOP+poker&hl=en&gl=US&ceid=US:en",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },
  {
    name: "note — ポーカー",
    slug: "note-poker",
    type: "RSS",
    url: "https://note.com/hashtag/ポーカー",
    feedUrl: "https://note.com/hashtag/%E3%83%9D%E3%83%BC%E3%82%AB%E3%83%BC/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["poker"],
  },

  // === AV（アダルトビデオ業界情報） ===
  {
    name: "FANZA ニュースリリース",
    slug: "fanza-news",
    type: "OFFICIAL",
    url: "https://www.dmm.co.jp/digital/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "FANZA公式サイト。ランキング・新着情報の要約のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "FANZA 売上ランキング",
    slug: "fanza-sales-ranking",
    type: "OFFICIAL",
    url: "https://www.dmm.co.jp/digital/videoa/-/ranking/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "FANZA公式ランキング。順位情報の要約のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "FANZA 新作情報",
    slug: "fanza-new-releases",
    type: "OFFICIAL",
    url: "https://www.dmm.co.jp/digital/videoa/-/list/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "FANZA公式新作一覧。タイトル・発売日の要約のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "moodyz 新作情報",
    slug: "moodyz-new",
    type: "OFFICIAL",
    url: "https://www.moodyz.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "S1 新作情報",
    slug: "s1-new",
    type: "OFFICIAL",
    url: "https://www.s1s1s1.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "Prestige 新作情報",
    slug: "prestige-new",
    type: "OFFICIAL",
    url: "https://www.prestige-av.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "Prestige公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "Idea Pocket 新作情報",
    slug: "ideapocket-new",
    type: "OFFICIAL",
    url: "https://www.ideapocket.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "IdeaPocket公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "FALENO 新作情報",
    slug: "faleno-new",
    type: "OFFICIAL",
    url: "https://faleno.jp/top/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "FALENO公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "Attackers 新作情報",
    slug: "attackers-new",
    type: "OFFICIAL",
    url: "https://www.attackers.net/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "Attackers公式サイト新作情報。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "SOD (Soft On Demand)",
    slug: "sod-new",
    type: "OFFICIAL",
    url: "https://www.sod.co.jp/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "SOD公式サイト。新作情報の要約のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "FANZA Magazine",
    slug: "fanza-magazine",
    type: "OFFICIAL",
    url: "https://magazine.fanza.com/",
    fetchMethod: "html",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "FANZA Magazine公式。業界分析・インタビューの要約のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "DMM プレスリリース",
    slug: "dmm-press",
    type: "OFFICIAL",
    url: "https://dmm-corp.com/press/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "DMM公式プレスリリース。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "Google News — AV業界速報",
    slug: "gnews-av",
    type: "RSS",
    url: "https://news.google.com/search?q=AV+新作+女優",
    feedUrl: "https://news.google.com/rss/search?q=AV+%E6%96%B0%E4%BD%9C+%E5%A5%B3%E5%84%AA&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "Google News — FANZA",
    slug: "gnews-fanza",
    type: "RSS",
    url: "https://news.google.com/search?q=FANZA+ランキング",
    feedUrl: "https://news.google.com/rss/search?q=FANZA+%E3%83%A9%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 50,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["av"],
  },
  {
    name: "note — AV業界",
    slug: "note-av",
    type: "RSS",
    url: "https://note.com/hashtag/AV",
    feedUrl: "https://note.com/hashtag/AV/rss",
    fetchMethod: "rss",
    trustScore: 40,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["av"],
  },

  // === 大阪ローカル ===
  {
    name: "大阪オンライン — イベント",
    slug: "osaka-online-events",
    type: "RSS",
    url: "https://osaka-online.jp/",
    fetchMethod: "html",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "大阪オンライン。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
  {
    name: "ウォーカープラス大阪 — グルメ",
    slug: "walkerplus-osaka-gourmet",
    type: "RSS",
    url: "https://www.walkerplus.com/event_list/ar0727/eg0117/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "ウォーカープラス。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
  {
    name: "食べログ大阪 — 新規オープン",
    slug: "tabelog-osaka-new",
    type: "RSS",
    url: "https://tabelog.com/osaka/C27100/rstLst/cond16-00-00/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "食べログ。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },

  // === 起業（スタートアップ） ===
  {
    name: "TechCrunch Japan",
    slug: "techcrunch-japan",
    type: "RSS",
    url: "https://jp.techcrunch.com/",
    feedUrl: "https://jp.techcrunch.com/feed/",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "TechCrunch Japan RSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "PR TIMES — スタートアップ",
    slug: "prtimes-startup",
    type: "RSS",
    url: "https://prtimes.jp/topics/keywords/スタートアップ",
    feedUrl: "https://prtimes.jp/topics/keywords/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%A2%E3%83%83%E3%83%97/feed",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "PR TIMES RSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "BRIDGE — スタートアップニュース",
    slug: "bridge-startup",
    type: "RSS",
    url: "https://thebridge.jp/",
    feedUrl: "https://thebridge.jp/feed",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "BRIDGE RSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "note — 起業",
    slug: "note-startup",
    type: "RSS",
    url: "https://note.com/hashtag/起業",
    feedUrl: "https://note.com/hashtag/%E8%B5%B7%E6%A5%AD/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "note — スタートアップ",
    slug: "note-startup-tag",
    type: "RSS",
    url: "https://note.com/hashtag/スタートアップ",
    feedUrl: "https://note.com/hashtag/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%A2%E3%83%83%E3%83%97/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },

  // === ウズベキスタン ===
  {
    name: "在日ウズベキスタン大使館",
    slug: "uzbek-embassy-japan",
    type: "OFFICIAL",
    url: "https://uzbekistan.jp/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "大使館公式サイト。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },
  {
    name: "JETRO — ウズベキスタン",
    slug: "jetro-uzbekistan",
    type: "OFFICIAL",
    url: "https://www.jetro.go.jp/world/russia_cis/uz/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "JETRO公式サイト。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },
  {
    name: "note — ウズベキスタン",
    slug: "note-uzbekistan",
    type: "RSS",
    url: "https://note.com/hashtag/ウズベキスタン",
    feedUrl: "https://note.com/hashtag/%E3%82%A6%E3%82%BA%E3%83%99%E3%82%AD%E3%82%B9%E3%82%BF%E3%83%B3/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },

  // === ホテル・ホテルマネジメント ===
  {
    name: "トラベルジャーナル",
    slug: "travel-journal",
    type: "OFFICIAL",
    url: "https://www.tjnet.co.jp/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "トラベルジャーナル公式サイト。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "観光経済新聞",
    slug: "kankokeizai",
    type: "OFFICIAL",
    url: "https://www.kankokeizai.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "観光経済新聞公式サイト。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "HOTERES — ホテル業界ニュース",
    slug: "hoteres-news",
    type: "OFFICIAL",
    url: "https://www.hoteresonline.com/",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "HOTERES公式サイト。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "note — ホテル",
    slug: "note-hotel",
    type: "RSS",
    url: "https://note.com/hashtag/ホテル",
    feedUrl: "https://note.com/hashtag/%E3%83%9B%E3%83%86%E3%83%AB/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },

  // === 香水 ===
  {
    name: "Fragrantica — 新着香水",
    slug: "fragrantica-new",
    type: "OFFICIAL",
    url: "https://www.fragrantica.com/newperfumes/",
    fetchMethod: "html",
    trustScore: 85,
    frequency: "HOURLY",
    legalNotes: "Fragrantica公式サイト。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "note — 香水",
    slug: "note-perfume",
    type: "RSS",
    url: "https://note.com/hashtag/香水",
    feedUrl: "https://note.com/hashtag/%E9%A6%99%E6%B0%B4/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "Zenn — 香水",
    slug: "zenn-perfume",
    type: "RSS",
    url: "https://zenn.dev/topics/perfume",
    feedUrl: "https://zenn.dev/topics/perfume/feed",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "ZennのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "@cosme — 香水ランキング",
    slug: "cosme-perfume-ranking",
    type: "OFFICIAL",
    url: "https://www.cosme.net/rankings/category/0110009",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "@cosme公式サイト。ランキング要約のみ。",
    productTagSlugs: ["perfume"],
  },

  // === ガジェット ===
  {
    name: "GIZMODO Japan",
    slug: "gizmodo-japan",
    type: "RSS",
    url: "https://www.gizmodo.jp/",
    feedUrl: "https://www.gizmodo.jp/feed/",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "GIZMODO Japan RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "Engadget 日本版",
    slug: "engadget-japan",
    type: "RSS",
    url: "https://japanese.engadget.com/",
    feedUrl: "https://japanese.engadget.com/rss.xml",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "Engadget日本版RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "note — ガジェット",
    slug: "note-gadget",
    type: "RSS",
    url: "https://note.com/hashtag/ガジェット",
    feedUrl: "https://note.com/hashtag/%E3%82%AC%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88/rss",
    fetchMethod: "rss",
    trustScore: 45,
    frequency: "HOURLY",
    legalNotes: "noteのRSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "ITmedia — ガジェット",
    slug: "itmedia-gadget",
    type: "RSS",
    url: "https://www.itmedia.co.jp/mobile/",
    feedUrl: "https://rss.itmedia.co.jp/rss/2.0/mobile.xml",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "ITmedia RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },

  // === 大阪風俗 ===
  {
    name: "シティヘブンネット大阪",
    slug: "cityheaven-osaka",
    type: "OFFICIAL",
    url: "https://cityheaven.net/osaka/",
    fetchMethod: "html",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "シティヘブンネット公式サイト。店舗情報の要約のみ。",
    productTagSlugs: ["osaka-fuzoku"],
  },
  {
    name: "ヘブンネット大阪 — ミナミ",
    slug: "cityheaven-osaka-minami",
    type: "OFFICIAL",
    url: "https://cityheaven.net/osaka/A2701/",
    fetchMethod: "html",
    trustScore: 70,
    frequency: "HOURLY",
    legalNotes: "シティヘブンネット公式サイト。ミナミエリア店舗情報の要約のみ。",
    productTagSlugs: ["osaka-fuzoku", "minami"],
  },
  {
    name: "風俗じゃぱん大阪",
    slug: "fuzoku-japan-osaka",
    type: "OFFICIAL",
    url: "https://fuzoku.jp/osaka/",
    fetchMethod: "html",
    trustScore: 65,
    frequency: "HOURLY",
    legalNotes: "風俗じゃぱん公式サイト。店舗情報の要約のみ。",
    productTagSlugs: ["osaka-fuzoku"],
  },
  {
    name: "ぴゅあらば大阪",
    slug: "purealba-osaka",
    type: "OFFICIAL",
    url: "https://www.cityheaven.net/osaka/",
    fetchMethod: "html",
    trustScore: 65,
    frequency: "HOURLY",
    legalNotes: "ぴゅあらば公式サイト。新人・イベント情報の要約のみ。",
    productTagSlugs: ["osaka-fuzoku"],
  },
  {
    name: "Google News — 大阪風俗",
    slug: "gnews-osaka-fuzoku",
    type: "RSS",
    url: "https://news.google.com/search?q=大阪+風俗+新店",
    feedUrl: "https://news.google.com/rss/search?q=%E5%A4%A7%E9%98%AA+%E9%A2%A8%E4%BF%97+%E6%96%B0%E5%BA%97&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 40,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["osaka-fuzoku"],
  },

  // ============================================
  // === Google News RSS — 全カテゴリ横断速報 ===
  // ============================================

  // --- AI速報 ---
  {
    name: "Google News — ChatGPT速報",
    slug: "gnews-chatgpt",
    type: "RSS",
    url: "https://news.google.com/search?q=ChatGPT",
    feedUrl: "https://news.google.com/rss/search?q=ChatGPT&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["chatgpt"],
  },
  {
    name: "Google News — Claude AI速報",
    slug: "gnews-claude",
    type: "RSS",
    url: "https://news.google.com/search?q=Claude+Anthropic",
    feedUrl: "https://news.google.com/rss/search?q=Claude+Anthropic&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["claude"],
  },
  {
    name: "Google News — Gemini速報",
    slug: "gnews-gemini",
    type: "RSS",
    url: "https://news.google.com/search?q=Gemini+Google+AI",
    feedUrl: "https://news.google.com/rss/search?q=Gemini+Google+AI&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Google News — 生成AI速報",
    slug: "gnews-generative-ai",
    type: "RSS",
    url: "https://news.google.com/search?q=生成AI",
    feedUrl: "https://news.google.com/rss/search?q=%E7%94%9F%E6%88%90AI&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["chatgpt", "claude", "gemini"],
  },
  {
    name: "Google News — OpenAI速報(EN)",
    slug: "gnews-openai-en",
    type: "RSS",
    url: "https://news.google.com/search?q=OpenAI",
    feedUrl: "https://news.google.com/rss/search?q=OpenAI&hl=en&gl=US&ceid=US:en",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS (English)。要約・引用のみ。",
    productTagSlugs: ["chatgpt", "openai-api"],
  },

  // --- AI公式ブログ（一次情報） ---
  {
    name: "OpenAI Blog",
    slug: "openai-blog",
    type: "OFFICIAL",
    url: "https://openai.com/blog",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "OpenAI公式ブログ。要約・引用のみ。",
    productTagSlugs: ["chatgpt", "openai-api"],
  },
  {
    name: "Anthropic News",
    slug: "anthropic-news",
    type: "OFFICIAL",
    url: "https://www.anthropic.com/news",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "Anthropic公式ニュース。要約・引用のみ。",
    productTagSlugs: ["claude", "claude-code"],
  },
  {
    name: "Google AI Blog",
    slug: "google-ai-blog",
    type: "OFFICIAL",
    url: "https://blog.google/technology/ai/",
    fetchMethod: "html",
    trustScore: 95,
    frequency: "HOURLY",
    legalNotes: "Google AI公式ブログ。要約・引用のみ。",
    productTagSlugs: ["gemini"],
  },
  {
    name: "Meta AI Blog",
    slug: "meta-ai-blog",
    type: "OFFICIAL",
    url: "https://ai.meta.com/blog/",
    fetchMethod: "html",
    trustScore: 90,
    frequency: "HOURLY",
    legalNotes: "Meta AI公式ブログ。要約・引用のみ。",
    productTagSlugs: [],
  },
  {
    name: "Hugging Face Blog",
    slug: "huggingface-blog",
    type: "RSS",
    url: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "Hugging Face公式ブログ。要約・引用のみ。",
    productTagSlugs: [],
  },

  // --- 起業 Google News ---
  {
    name: "Google News — スタートアップ資金調達",
    slug: "gnews-startup-funding",
    type: "RSS",
    url: "https://news.google.com/search?q=スタートアップ+資金調達",
    feedUrl: "https://news.google.com/rss/search?q=%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%A2%E3%83%83%E3%83%97+%E8%B3%87%E9%87%91%E8%AA%BF%E9%81%94&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },
  {
    name: "Coral Capital Blog",
    slug: "coral-capital-blog",
    type: "RSS",
    url: "https://coralcap.co/blog/",
    feedUrl: "https://coralcap.co/feed/",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "Coral Capital公式ブログ。要約・引用のみ。",
    productTagSlugs: ["startup"],
  },

  // --- ウズベキスタン Google News ---
  {
    name: "Google News — ウズベキスタン",
    slug: "gnews-uzbekistan",
    type: "RSS",
    url: "https://news.google.com/search?q=ウズベキスタン",
    feedUrl: "https://news.google.com/rss/search?q=%E3%82%A6%E3%82%BA%E3%83%99%E3%82%AD%E3%82%B9%E3%82%BF%E3%83%B3&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },
  {
    name: "Google News — Uzbekistan(EN)",
    slug: "gnews-uzbekistan-en",
    type: "RSS",
    url: "https://news.google.com/search?q=Uzbekistan",
    feedUrl: "https://news.google.com/rss/search?q=Uzbekistan&hl=en&gl=US&ceid=US:en",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS (English)。要約・引用のみ。",
    productTagSlugs: ["uzbekistan"],
  },

  // --- ホテル Google News ---
  {
    name: "Google News — ホテル開業",
    slug: "gnews-hotel",
    type: "RSS",
    url: "https://news.google.com/search?q=ホテル+開業+新規",
    feedUrl: "https://news.google.com/rss/search?q=%E3%83%9B%E3%83%86%E3%83%AB+%E9%96%8B%E6%A5%AD+%E6%96%B0%E8%A6%8F&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },
  {
    name: "トラベルWatch",
    slug: "travel-watch",
    type: "RSS",
    url: "https://travel.watch.impress.co.jp/",
    feedUrl: "https://travel.watch.impress.co.jp/data/rss/1.0/tvw/feed.rdf",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "トラベルWatch RSSフィード。要約・引用のみ。",
    productTagSlugs: ["hotel"],
  },

  // --- 香水 Google News ---
  {
    name: "Google News — 新作香水",
    slug: "gnews-perfume",
    type: "RSS",
    url: "https://news.google.com/search?q=新作+香水+フレグランス",
    feedUrl: "https://news.google.com/rss/search?q=%E6%96%B0%E4%BD%9C+%E9%A6%99%E6%B0%B4+%E3%83%95%E3%83%AC%E3%82%B0%E3%83%A9%E3%83%B3%E3%82%B9&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },
  {
    name: "WWD Japan — ビューティ",
    slug: "wwd-japan-beauty",
    type: "OFFICIAL",
    url: "https://www.wwdjapan.com/beauty",
    fetchMethod: "html",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "WWD Japan公式サイト。要約・引用のみ。",
    productTagSlugs: ["perfume"],
  },

  // --- ガジェット Google News ---
  {
    name: "Google News — ガジェット",
    slug: "gnews-gadget",
    type: "RSS",
    url: "https://news.google.com/search?q=ガジェット+レビュー+新製品",
    feedUrl: "https://news.google.com/rss/search?q=%E3%82%AC%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88+%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC+%E6%96%B0%E8%A3%BD%E5%93%81&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "PC Watch",
    slug: "pc-watch",
    type: "RSS",
    url: "https://pc.watch.impress.co.jp/",
    feedUrl: "https://pc.watch.impress.co.jp/data/rss/1.0/pcw/feed.rdf",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "PC Watch RSSフィード。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },
  {
    name: "AV Watch",
    slug: "av-watch",
    type: "RSS",
    url: "https://av.watch.impress.co.jp/",
    feedUrl: "https://av.watch.impress.co.jp/data/rss/1.0/avw/feed.rdf",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "AV Watch RSSフィード（オーディオ・ビジュアル機器）。要約・引用のみ。",
    productTagSlugs: ["gadget"],
  },

  // --- 大阪ローカル Google News ---
  {
    name: "Google News — 大阪ニュース",
    slug: "gnews-osaka",
    type: "RSS",
    url: "https://news.google.com/search?q=大阪+ニュース+新店",
    feedUrl: "https://news.google.com/rss/search?q=%E5%A4%A7%E9%98%AA+%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9+%E6%96%B0%E5%BA%97&hl=ja&gl=JP&ceid=JP:ja",
    fetchMethod: "rss",
    trustScore: 60,
    frequency: "HOURLY",
    legalNotes: "Google News RSS。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
  {
    name: "Lmaga.jp — 関西ニュース",
    slug: "lmaga-kansai",
    type: "RSS",
    url: "https://www.lmaga.jp/",
    feedUrl: "https://www.lmaga.jp/feed/",
    fetchMethod: "rss",
    trustScore: 80,
    frequency: "HOURLY",
    legalNotes: "Lmaga.jp RSSフィード。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
  {
    name: "なんば経済新聞",
    slug: "namba-keizai",
    type: "RSS",
    url: "https://namba.keizai.biz/",
    feedUrl: "https://namba.keizai.biz/rss/",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "なんば経済新聞RSSフィード。要約・引用のみ。",
    productTagSlugs: ["osaka-local", "minami"],
  },
  {
    name: "梅田経済新聞",
    slug: "umeda-keizai",
    type: "RSS",
    url: "https://umeda.keizai.biz/",
    feedUrl: "https://umeda.keizai.biz/rss/",
    fetchMethod: "rss",
    trustScore: 75,
    frequency: "HOURLY",
    legalNotes: "梅田経済新聞RSSフィード。要約・引用のみ。",
    productTagSlugs: ["osaka-local"],
  },
];
